// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtlxdbokhtdtfmziacai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0bHhkYm9raHRkdGZtemlhY2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzg3MTQsImV4cCI6MjA3NDcxNDcxNH0.MWmxtQSnOjDW_U1L7QicRyuw7lk44EphfEcuJ5oobGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});